[build]
  command = "npm install --save dotenv && npm install --save node-fetch@2"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.111.3"

[context.production]
  command = "hugo"

[context.branch-deploy]
  command = "hugo --environment staging"

[functions]
  node_bundler = "esbuild"
