[[main]]
name = "Home"
url = ""
weight = "-111"
[[main]]
name = "Blog Posts"
url = "post/"
weight = "-110"
[[main]]
name = "About"
url = "about/"
weight = "-109"
[[main]]
name = "Contact"
url = "contact/"
weight = "-108"
[[main]]
name = "Contribute"
url = "contribute/"
weight = "-107"
[[main]]
name = "Forums"
url = "https://forum.techrelay.xyz/"
weight = "-106"
[[main]]
name = "Archives"
url = "archives/"
weight = "-105"
[[main]]
identifier = "Links"
name = "Links"
weight = "-104"
[[main]]
name = "Snippets & Scripts"
parent = "Links"
url = "snippets/"
[[main]]
name = "Trauma To Travel"
parent = "Links"
url = "https://traumatotravel.xyz"
[[main]]
name = "Build Status"
parent = "Links"
url = "status/"
[[main]]
name = "CV/Résumé"
parent = "Links"
url = "https://nbennett.pro"
[[main]]
name = "Affiliate Links"
parent = "Links"
url = "https://techrelay.xyz/affiliate"
[[main]]
name = "Tech/IT Services"
parent = "Links"
url = "https://techrelay.xyz/services"
[[main]]
name = "Testimonials"
parent = "Links"
url = "https://techrelay.xyz/testimonials/"
[[social]]
name = "github"
type = "social"
url = "https://github.com/techrelay"
weight = 1
[[social]]
name = "twitter"
url = "https://twitter.com/_zippyy_"
weight = 2
[[social]]
name = "rss"
url = "index.xml"
weight = 4
