[[main]]
name = "Home"
url = ""
weight = "-111"
[[main]]
name = "Blog Posts"
url = "post/"
weight = "-110"
[[main]]
name = "About"
url = "about/"
weight = "-109"
[[main]]
name = "Contact"
url = "contact/"
weight = "-108"
[[main]]
name = "Contribute"
url = "contribute/"
weight = "-107"
[[main]]
name = "Archives"
url = "archives/"
weight = "-106"
[[main]]
identifier = "Links"
name = "Links"
weight = "-105"
[[main]]
name = "Snippets & Scripts"
parent = "Links"
url = "https://techrelay.xyz/snippets"
[[main]]
name = "Trauma To Travel"
parent = "Links"
url = "https://traumatotravel.xyz"
[[main]]
name = "Build Status"
parent = "Links"
url = "https://techrelay.xyz/status"
[[social]]
name = "github"
type = "social"
url = "https://github.com/techrelay"
weight = 1
[[social]]
name = "twitter"
url = "https://twitter.com/_zippyy_"
weight = 2
[[social]]
name = "rss"
url = "index.xml"
weight = 4
